import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
const read=name=>readFile(new URL('./src/'+name,import.meta.url),'utf8');
const [shell,css,accountCSS,app,cloud,helpers,validator,backup,data]=await Promise.all(['shell.html','style.css','account.css','app.js','cloud-client.js','state-sync.js','validate.js','backup.js','content.json'].map(read));
await build({entryPoints:['src/independent-client.js'],bundle:true,format:'iife',target:'es2022',outfile:'independent-client.js',minify:true,legalComments:'eof'});
const study=`'use strict';\n(async()=>{await window.FundLocal.ready;await window.FundIndependent.ready;window.__FUND_CLOUD__=!window.FundIndependent.localMode;\n${helpers}\n${validator}\n${app.replace('__CLOUD_CLIENT__',cloud+'\n'+backup)}\n})().catch(()=>{document.getElementById('app').innerHTML='<div class="cloud-loading"><h1>暂时无法打开账号</h1><p>可以重新登录，或先在本机学习。</p><a class="btn primary" href="./account.html">重新登录</a><p><a href="./?local=1">本机学习</a></p></div>';});`;
await writeFile('study.js',study);await writeFile('style.css',css+'\n'+accountCSS);
const csp="default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src data:; connect-src 'self'; base-uri 'none'; form-action 'none'; object-src 'none'";
const hash=text=>createHash('sha256').update(text).digest('hex').slice(0,12);
const client=await readFile('independent-client.js','utf8'),config=await readFile('config.js','utf8');
await copyFile('src/local-auth.js','local-auth.js');
const localAuth=await readFile('local-auth.js','utf8');
const scripts=`<script defer src="./local-auth.js?v=${hash(localAuth)}"></script><script defer src="./config.js?v=${hash(config)}"></script><script defer src="./independent-client.js?v=${hash(client)}"></script>`;
let html=shell.replace('<style>__CSS__</style>',`<link rel="stylesheet" href="./style.css?v=${hash(css+accountCSS)}">`).replace('</head>',`<meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="${csp}"></head>`);
const head=html.split('<body>')[0];
html=html.replace('__DATA__',data.replaceAll('</','<\\/')).replace('<script>__JS__</script>',scripts+`<script defer src="./study.js?v=${hash(study)}"></script>`);
await writeFile('index.html',html);
const account=head+'<body class="account-body"><main class="account-wrap" id="local-account-root"><p>正在打开账号页…</p></main>'+scripts+'</body></html>';
await writeFile('account.html',account);await writeFile('login.html',account);
await writeFile('pages-client.js','// Compatibility file: the independent edition uses independent-client.js.\n');
await writeFile('.nojekyll','');await copyFile('src/content.json','content.json');
const edge='supabase/functions/fund-study/';await mkdir(edge,{recursive:true});
for(const name of ['state-sync.js','validate.js'])await copyFile('src/'+name,edge+name);
const content=JSON.parse(data);await writeFile(edge+'content.json',JSON.stringify({questions:content.questions.map(({id,answer,subject,topic})=>({id,answer,subject,topic})),lessons:content.lessons.map(({id})=>({id}))}));
console.log('Built independent GitHub Pages website and Supabase function.');
