globalThis.createFundValidator=function(DATA){
const QUESTIONS=Object.fromEntries(DATA.questions.map(q=>[q.id,{answer:q.answer,subject:q.subject,topic:q.topic}]));
const ANSWERS=Object.fromEntries(DATA.questions.map(q=>[q.id,q.answer]));
const LESSON_IDS=new Set(DATA.lessons.map(l=>l.id));
const dict=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const finite=x=>Number.isFinite(x)&&x>=0;
const answer=x=>x===null||Number.isInteger(x)&&x>=0&&x<=3;
function validSession(p,exam=false){if(!dict(p)||![1,3].includes(p.subject)||!Array.isArray(p.ids)||!p.ids.length||p.ids.length>322||new Set(p.ids).size!==p.ids.length)return false;if(p.ids.some(id=>!QUESTIONS[id]||QUESTIONS[id].subject!==p.subject))return false;if(!dict(p.answers)||Object.entries(p.answers).some(([id,a])=>!p.ids.includes(id)||!answer(a)))return false;if(exam&&(typeof p.id!=='string'||p.id.length>180||p.ids.length!==100||!finite(p.start)||p.deadline!==p.start+7200000))return false;if(!exam&&(!Number.isInteger(p.index)||p.index<0||p.index>=p.ids.length||!dict(p.checked)))return false;return true;}
function validate(input){if(!dict(input)||input.schema!==1||![5,8,10].includes(input.hours))throw Error('invalid_state');for(const key of ['learned','planDone','stats','baselineStats','attemptLog','_clock'])if(!dict(input[key]))throw Error('invalid_'+key);if(Object.entries(input.learned).some(([key,v])=>!LESSON_IDS.has(key)||typeof v!=='boolean'))throw Error('invalid_lessons');if(Object.entries(input.planDone).some(([key,v])=>key.length>80||typeof v!=='boolean'))throw Error('invalid_plan');if(Object.keys(input.attemptLog).length>12000)throw Error('too_many_attempts');for(const [id,e] of Object.entries(input.attemptLog))if(!dict(e)||id.length>300||e.id!==id||!QUESTIONS[e.question]||!answer(e.answer)||!finite(e.at))throw Error('invalid_attempt');for(const [id,s] of Object.entries(input.baselineStats))if(!QUESTIONS[id]||!dict(s)||!['attempts','correct','wrong','streak'].every(k=>Number.isInteger(s[k])&&s[k]>=0)||s.attempts!==s.correct+s.wrong||!answer(s.last??null))throw Error('invalid_baseline');if(!Array.isArray(input.history)||input.history.length>30||input.history.some(h=>!validSession(h,true)||!finite(h.endedAt)))throw Error('invalid_history');if(input.activeExam!==null&&!validSession(input.activeExam,true))throw Error('invalid_exam');if(input.practice!==null&&!validSession(input.practice))throw Error('invalid_practice');if(Object.values(input._clock).some(n=>!finite(n)))throw Error('invalid_clock');
const state=globalThis.FundState.upgrade(input);for(const h of state.history){let score=0,unanswered=0;h.topicResults={};for(const id of h.ids){const q=QUESTIONS[id],a=h.answers[id],ok=a===q.answer;if(ok)score++;if(!Number.isInteger(a))unanswered++;const t=h.topicResults[q.topic]||={correct:0,total:0};t.total++;if(ok)t.correct++;}Object.assign(h,{score,unanswered,wrong:100-score-unanswered,passed:score>=60});h.elapsed=Math.min(7200,Math.max(0,Math.floor((Math.min(h.endedAt,h.deadline)-h.start)/1000)));for(const id of (h.legacyRecorded?[]:h.ids)){const key=h.id+'/'+id;state.attemptLog[key]={id:key,question:id,answer:h.answers[id]??null,at:h.endedAt};}}
if(state.activeExam&&state.history.some(h=>h.id===state.activeExam.id))state.activeExam=null;return globalThis.FundState.recompute(state,ANSWERS);}

return input=>{const s=JSON.stringify(input);if(s.length>1500000||/"(?:__proto__|constructor|prototype)"\s*:/.test(s))throw Error('invalid_state');return validate(input)};
};
