const apiFetch=(...args)=>window.FundAPI?window.FundAPI.fetch(...args):fetch(...args);
// Included inside app.js's closure by the build; state and rendering remain shared.
function cloudCache(){if(!cloud.userId)return;try{localStorage.setItem(KEY+'-cloud-draft:'+encodeURIComponent(cloud.userId),JSON.stringify({userId:cloud.userId,revision:cloud.revision,dirty:cloud.dirty,state}));}catch{/* A pending draft is optional; the database is the saved record. */}}
function cloudStatus(){return cloud.phase==='saving'?'正在保存到云端':cloud.phase==='pending'?'有待保存的记录':cloud.phase==='offline'?'尚未同步 · 点击重试':cloud.phase==='error'?'云端暂不可用 · 点击重试':'已保存到云端';}
function paintCloudStatus(){document.querySelectorAll('[data-cloud-status]').forEach(el=>{el.textContent=cloudStatus();el.classList.toggle('unsynced',cloud.dirty||cloud.phase==='offline'||cloud.phase==='error');});document.querySelectorAll('[data-cloud-warning]').forEach(el=>{el.hidden=!['offline','error'].includes(cloud.phase);el.textContent=cloud.ready?'当前连接不可用，新作答尚未保存到云端。恢复网络后会重试；离开前请确认右上角显示“已保存到云端”。':'暂时无法读取云端记录，请重试。';});}
function scheduleCloud(){if(!CLOUD_ENABLED||!cloud.ready)return;clearTimeout(cloud.saveTimer);cloud.saveTimer=setTimeout(()=>flushCloud(),180);}
async function getCloud(){const response=await apiFetch('/api/progress',{credentials:'same-origin',cache:'no-store'});if(response.status===401){cloudCache();cloud.ready=false;cloud.phase='signedout';render();throw Error('sign_in_required');}if(!response.ok)throw Error('cloud_load_failed');const result=await response.json();if(typeof result.userId!=='string'||!Number.isInteger(result.revision))throw Error('invalid_cloud_response');return result;}
async function bootstrapCloud(){if(cloud.loading)return;cloud.loading=true;cloud.phase='loading';render();try{const remote=await getCloud();let draft=null;try{const saved=JSON.parse(localStorage.getItem(KEY+'-cloud-draft:'+encodeURIComponent(remote.userId))||localStorage.getItem(KEY+'-cloud-draft')||'null');if(saved?.userId===remote.userId&&saved.state)draft=saved;}catch{}
cloud.userId=remote.userId;cloud.account=remote.account;cloud.revision=remote.revision;let local=FundState.fresh();if(draft)local=FundState.upgrade(draft.state);else if(remote.account?.kind==='chatgpt'){try{const owner=localStorage.getItem(KEY+'-legacy-owner');if(!owner||owner===remote.userId){local=state;localStorage.setItem(KEY+'-legacy-owner',remote.userId);}}catch{local=FundState.fresh();}}const answers=Object.fromEntries(BANK.map(q=>[q.id,q.answer]));
if(remote.state){state=draft?.dirty?FundState.merge(local,remote.state,answers):FundState.upgrade(remote.state);cloud.dirty=!!draft?.dirty;}else{state=FundState.upgrade(local);FundState.stamp(state,FundState.fresh());cloud.dirty=true;}
lastCaptured=FundState.clone(state);cloud.ready=true;cloud.phase=cloud.dirty?'pending':'saved';cloudCache();if(state.activeExam)tab='exam';render();checkDeadline();if(cloud.dirty)await flushCloud();}
catch(err){cloud.phase=err.message==='sign_in_required'?'signedout':'error';render();}finally{cloud.loading=false;}}
async function flushCloud({keepalive=false}={}){if(!CLOUD_ENABLED||!cloud.ready||cloud.inFlight||!cloud.dirty)return;cloud.inFlight=true;cloud.phase='saving';paintCloudStatus();try{for(let attempt=0;attempt<4;attempt++){const generation=cloud.generation;const payload=JSON.stringify({userId:cloud.userId,revision:cloud.revision,state});if(keepalive&&new TextEncoder().encode(payload).length>60000)break;const response=await apiFetch('/api/progress',{method:'PUT',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:payload,keepalive});if(response.status===401){cloud.phase='signedout';cloud.ready=false;render();throw Error('sign_in_required');}if(!response.ok&&response.status!==409)throw Error('cloud_save_failed');const remote=await response.json();if(remote.userId!==cloud.userId)throw Error('account_changed');const answers=Object.fromEntries(BANK.map(q=>[q.id,q.answer]));cloud.revision=remote.revision;
if(response.status===409){state=FundState.merge(state,remote.state,answers);lastCaptured=FundState.clone(state);cloud.dirty=true;cloudCache();if(state.activeExam)tab='exam';render();continue;}
state=cloud.generation===generation?FundState.upgrade(remote.state):FundState.merge(state,remote.state,answers);lastCaptured=FundState.clone(state);cloud.dirty=cloud.generation!==generation;cloud.phase=cloud.dirty?'pending':'saved';cloudCache();paintCloudStatus();if(!cloud.dirty)break;}
if(cloud.dirty&&cloud.phase!=='signedout')cloud.phase='pending';}
catch(err){if(cloud.phase!=='signedout')cloud.phase='offline';cloud.dirty=true;cloudCache();paintCloudStatus();}
finally{cloud.inFlight=false;paintCloudStatus();if(cloud.dirty&&cloud.phase==='pending'&&!keepalive)scheduleCloud();}}
async function refreshCloud(){if(!cloud.ready||cloud.inFlight||cloud.dirty||document.hidden)return;try{const remote=await getCloud();if(remote.userId!==cloud.userId){cloud.ready=false;cloud.phase='signedout';render();return;}if(remote.revision>cloud.revision){state=FundState.upgrade(remote.state);cloud.revision=remote.revision;lastCaptured=FundState.clone(state);cloud.phase='saved';cloudCache();if(state.activeExam)tab='exam';render();checkDeadline();}cloud.phase='saved';paintCloudStatus();}catch{if(cloud.phase==='signedout'){cloud.ready=false;render();}else{cloud.phase='error';paintCloudStatus();}}}

async function openAccount(){if(cloud.inFlight){toast('正在保存，请稍后再打开账号设置。');return;}if(cloud.dirty)await flushCloud();if(cloud.dirty){toast('还有未同步的记录，请恢复网络并保存后再打开账号设置。');return;}window.location.assign(window.FundAPI?window.FundAPI.path('account'):'/account');}
