'use strict';
(() => {
const clone=x=>JSON.parse(JSON.stringify(x));
const isObject=x=>x&&typeof x==='object'&&!Array.isArray(x);
const fresh=()=>({schema:1,hours:8,planDone:{},learned:{},stats:{},history:[],activeExam:null,practice:null,attemptLog:{},baselineStats:{},_clock:{}});
function upgrade(input){const s={...fresh(),...clone(input||{})};if(!isObject(input?.attemptLog))s.history=s.history.map(h=>({...h,legacyRecorded:true}));if(!isObject(s.attemptLog))s.attemptLog={};if(!isObject(input?.baselineStats))s.baselineStats=clone(s.stats||{});if(!isObject(s._clock))s._clock={};if(s.practice&&!s.practice.runId)s.practice.runId='practice-'+s.practice.startedAt+'-'+s.practice.ids.join('-').slice(0,80);return s;}
function recompute(s,answers){const stats=clone(s.baselineStats||{});for(const e of Object.values(s.attemptLog||{}).sort((a,b)=>a.at-b.at||a.id.localeCompare(b.id))){if(!Object.hasOwn(answers,e.question))continue;const r=stats[e.question]||{attempts:0,correct:0,wrong:0,streak:0,wasWrong:false};const correct=answers[e.question]===e.answer;r.attempts++;r.last=e.answer;r.lastAt=e.at;if(correct){r.correct++;r.streak=(r.streak||0)+1;}else{r.wrong++;r.streak=0;r.wasWrong=true;}stats[e.question]=r;}s.stats=stats;return s;}
function stamp(state,previous,now=Date.now()){state._clock||={};const old=previous||fresh();let tick=now;for(const n of Object.values(state._clock))if(Number.isFinite(n))tick=Math.max(tick,n+1);for(const field of['hours','activeExam','practice'])if(JSON.stringify(state[field])!==JSON.stringify(old[field]))state._clock[field]=tick;for(const field of['learned','planDone'])for(const key of new Set([...Object.keys(state[field]||{}),...Object.keys(old[field]||{})]))if(state[field]?.[key]!==old[field]?.[key])state._clock[field+'.'+key]=tick;for(const field of['activeExam','practice']){const current=state[field],before=old[field];if(!current)continue;current._answerTimes||={};current._flagTimes||={};for(const key of Object.keys(current.answers||{}))if(!before||current.answers[key]!==before.answers?.[key])current._answerTimes[key]=tick;for(const key of Object.keys(current.flags||{}))if(!before||current.flags[key]!==before.flags?.[key])current._flagTimes[key]=tick;if(JSON.stringify(current)!==JSON.stringify(before))current._changedAt=tick;}return state;}
function mergeSession(a,b,field,clockA,clockB){const left=clockA[field]||0,right=clockB[field]||0;const chosen=clone(left>right?a:b);if(!a||!b)return chosen;const idA=a.id||a.runId,idB=b.id||b.runId;if(idA!==idB)return chosen;const r=chosen;for(const [map,times] of[['answers','_answerTimes'],['flags','_flagTimes']]){r[map]={};r[times]={};for(const key of new Set([...Object.keys(a[map]||{}),...Object.keys(b[map]||{})])){const at=a[times]?.[key]||0,bt=b[times]?.[key]||0;const win=at>bt?a:b;if(Object.hasOwn(win[map]||{},key)){r[map][key]=win[map][key];r[times][key]=Math.max(at,bt);}else{const alt=win===a?b:a;r[map][key]=alt[map][key];r[times][key]=Math.max(at,bt);}}}if(field==='practice'){r.checked={...a.checked,...b.checked};r.completed=!!(a.completed||b.completed);}r._changedAt=Math.max(a._changedAt||0,b._changedAt||0);return r;}
function merge(local,remote,answers){const a=upgrade(local),b=upgrade(remote),r=upgrade(b);r._clock={...a._clock,...b._clock};for(const k of Object.keys(a._clock))r._clock[k]=Math.max(a._clock[k]||0,b._clock[k]||0);r.hours=(a._clock.hours||0)>(b._clock.hours||0)?a.hours:b.hours;for(const field of['learned','planDone']){r[field]={};for(const key of new Set([...Object.keys(a[field]),...Object.keys(b[field])])){const k=field+'.'+key;const v=(a._clock[k]||0)>(b._clock[k]||0)?a[field][key]:b[field][key];r[field][key]=v??a[field][key]??false;}}
r.baselineStats=clone(b.baselineStats);for(const [id,stat] of Object.entries(a.baselineStats))if(!r.baselineStats[id]||(stat.attempts||0)>(r.baselineStats[id].attempts||0))r.baselineStats[id]=clone(stat);
r.attemptLog={...a.attemptLog,...b.attemptLog};const history=new Map();for(const h of [...b.history,...a.history])if(!history.has(h.id)||h.endedAt<history.get(h.id).endedAt)history.set(h.id,h);r.history=[...history.values()].sort((x,y)=>y.endedAt-x.endedAt).slice(0,30);
// One deterministic answer event per exam/question prevents duplicate grading on another device.
for(const h of r.history.filter(h=>!h.legacyRecorded))for(const id of h.ids){const key=h.id+'/'+id;r.attemptLog[key]={id:key,question:id,answer:h.answers[id]??null,at:h.endedAt};}
r.activeExam=mergeSession(a.activeExam,b.activeExam,'activeExam',a._clock,b._clock);r.practice=mergeSession(a.practice,b.practice,'practice',a._clock,b._clock);if(r.activeExam&&history.has(r.activeExam.id))r.activeExam=null;return recompute(r,answers);}
globalThis.FundState={fresh,upgrade,recompute,stamp,merge,clone};
})();
